### ISSUE TITLE
Support new-build

### ISSUE THREAD

**Issue by nomeata** [dan-t/cabal-bounds#11]
I really like the idea of `cabal-bounds`. But my workflow is built around `cabal new-build` instead of sandboxes, and in such a setting it does not find the current versions, because it knows about `dist`, but not `dist-newstyle`:
```
~/projekte/programming/hledger/hledger-irr $ ~/.cabal/bin/cabal-bounds update -e foo
cabal-bounds: Couldn't find 'dist' directory! Have you already build the project?
```
Have you looked into supporting this workflow?

**Comment by nomeata** [comment]
`dist-newstyle/cache/plan.json` might be an easy to parser source for that information.

**Comment by dan-t** [comment]
It might be quite easy supporting `cabal new-build`.

The function `libraries` in `CabalBounds/Main.hs` already handles different cases for supplying
the libraries and their versions: from the build, a haskell platform version or from a file.

So adding support for the libraries from `dist-newstyle/cache/plan.json` should be quite straight forward.

**Comment by dan-t** [comment]
The current github version should now support `cabal new-build`. For now only `cabal 1.24` is supported, but I want to add support for `cabal 2`.

There's now the new subcommand `cabal-bounds libs` to just output the libraries and versions a `cabal-bounds update` run would use.

**Comment by dan-t** [comment]
`cabal-bounds 1.3` should now support `cabal new-build`.

Unfortunately `cabal 2.0` has a broken pretty printing of cabal files. So by
now there's only support for `cabal 1.24`.

**Comment by nomeata** [comment]
> Unfortunately cabal 2.0 has a broken pretty printing of cabal files. So by now there's only support for cabal 1.24.

Is there a upstream bug report for that?

**Comment by dan-t** [comment]
Seems to be already fixed.
