### ISSUE TITLE
Cabal’s lexicografic ordering and trailing zeros in version bounds

### ISSUE THREAD

**Issue by zkf** [dan-t/cabal-bounds#5]
When using `cabal-bounds` to update dependencies of a package, the bounds for *lens* were updated to `lens >=4.7.0 && <4.8`. However, on Hackage, *lens*’s most recent version is given as 4.7, without the trailing zero.

Now cabal is unable to resolve the dependencies because, according to the lexicografic ordering, 4.7 >= 4.7.0 = False.

**Comment by dan-t** [comment]
Now cabal is unable to resolve the dependencies because, according to
    the lexicografic ordering, 4.7 >= 4.7.0 = False.

@23Skidoo isn't this a cabal issue? I don't think that '4.7' and '4.7.0'
should really mean something different.

**Comment by 23Skidoo** [comment]
This is a `Data.Version` issue. IIRC there is a ticket for it either on the Cabal or GHC tracker somewhere.

**Comment by 23Skidoo** [comment]
https://github.com/haskell/cabal/issues/1368

**Comment by dan-t** [comment]
cabal-bounds 0.9.1 should now fix this.

**Comment by zkf** [comment]
Thanks!

**Comment by dan-t** [comment]
Unfortunately cabal-bounds 0.9.1 is broken, I will try to release 0.9.2 this evening.
