### ISSUE TITLE
unhandled argument on snippet from readme

### ISSUE THREAD

**Issue by lspitzner** [dan-t/cabal-bounds#6]
readme contains `cabal-bounds dump --output=libs.hs myproject.cabal`

but when i try that, i get:

~~~~.bash
$> cabal-bounds dump --output=libs.hs multistate.cabal 
Unhandled argument, none expected: multistate.cabal
~~~~

you probably should add a `-c`. or allow the free option.

**Comment by dan-t** [comment]
Should be fixed now with cabal-bounds 0.9.4.
