### ISSUE TITLE
write cabal.config / loosen bounds

### ISSUE THREAD

**Issue by lspitzner** [dan-t/cabal-bounds#7]
It would be nice if instead of changing the .cabal file, `cabal-bounds` could just print out a cabal.config (similar to what stackage does) with the exact versions of a haskell-platform release. That way
a) no annoying reformatting happens
b) i can still see relatively quickly which of my bounds conflict with some platform release.

Changing the .cabal file would also make sense, but only for loosening bounds. This is currently not possible, is it? I.e. "take current bounds, and loosen them sufficiently to work with platform xy". Together with printing cabal.config, this seems to enable fast workflows like
1. loosen bounds for platform xy and write the exact bounds into cabal.config
2. try to compile/test (using sandbox of course)
3. a) everything is fine -> delete cabal.config; b) fix fixable problems, then delete cabal.config or c) revert 1.

sorry if `cabal-bounds` supports such a workflow already, i may not have read the readme sufficiently carefully.

**Comment by dan-t** [comment]
What you're able to do is to set the versions to the ones of a haskell platform, try to
build it, rebuild with `--allow-newer`, and finally set the upper bounds to the ones of the build:
    cabal-bounds update --haskell-platform=2013.2.0.0 project.cabal
    cabal install
    cabal install --allow-newer
    cabal-bounds update --upper project.cabal dist/dist-sandbox-*/setup-config

I want to keep the scope of `cabal-bounds` on the cabal file and even in your
workflow you want to modify the cabal file at the end, so using a `cabal.config`
doesn't seem to give you that much.

I think a more common workflow is to start a project and initialize your bounds to the
ones of a haskell platform and then try to loosen the upper bounds.

**Comment by lspitzner** [comment]
but i could do any updates to the .cabal by hand, avoiding the reformatting. on the other hand, i ideally would want a tool to download `cabal.config`s for different platform or stackage versions, and this might certainly go beyond the intended scope of cabal-bounds.

**Comment by dan-t** [comment]
If you want to give a try on such a tool, have a look at the functions
`libraries`, `haskellPlatformLibraries` and `installedLibraries` inside of
`lib/CabalBounds/Main.hs`. I think it's quite straight forward to generate
a `cabal.config` from the result of these functions.

**Comment by lspitzner** [comment]
i already noticed you have nice hard-coded versions for the platform releases. where did you obtain those? just by looking at the contents of the tarballs?

**Comment by dan-t** [comment]
There has been a web side comparing the versions of the libraries for each haskell platform. But
I can't recall where it was.

**Comment by lspitzner** [comment]
i found https://github.com/haskell/haskell-platform/wiki/Library-VersionMatrix, but that seems outdated. i'll search some more / ask around.

Thansk for your replies.
