### ISSUE TITLE
drops `if` clause in `library`

### ISSUE THREAD

**Issue by sboosali** [dan-t/cabal-bounds#8]
e.g.

before:

    library
       if os(darwin)
           buildable: True
       else
           buildable: False
       exposed-modules: ...

after `cabal-bounds drop --executable=blub`:

    library
        if os(osx)
        else
            exposed-modules: ...

versions:

    cabal-bounds version 1.0.1
    The Glorious Glasgow Haskell Compilation System, version 7.10.1

**Comment by dan-t** [comment]
What I'm seeing is that

    if os(darwin)
        buildable: True
    else
        buildable: False

gets replaced by

    if os(osx)
    else
        buildable: False

I think the pretty printer of `Cabal` just leaves the `buildable: True`
out, because it's the default value.


Greetings,
Daniel

**Comment by sboosali** [comment]
with my version of cabal, that seems to be an error:

    $ cabal build
    cabal: ...: 'then' branch of 'if' is empty

    $ cabal --version 
    cabal-install version 1.22.6.0
    using version 1.22.2.0 of the Cabal library

**Comment by dan-t** [comment]
Ok, that's nasty. I would consider it a `cabal` bug.

As a workaround

    if !os(osx)
        buildable: False

**Comment by sboosali** [comment]
thanks. if it's a cabal pretty printer bug, I guess I should report it
there.

the workaround works.

On Wednesday, September 9, 2015, Daniel Trstenjak <notifications@github.com>
wrote:

> Closed #8 <https://github.com/dan-t/cabal-bounds/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dan-t/cabal-bounds/issues/8#event-404514311>.
>


-- 



*(this message was composed with dictation: charitably interpret typos)Sam
Boosalis*
