### ISSUE TITLE
Hpack?

### ISSUE THREAD

**Issue by kanishka-azimi** [dan-t/cabal-bounds#9]
Consider extending to support hpack. Thanks for considering

**Comment by dan-t** [comment]
> 
> Consider extending to support hpack. Thanks for considering
> 
The whole program and its options are tightly bound to the cabal
data structures. So supporting hpack would be a complete
rewrite and it makes more sense to have a separate program
for it.

**Comment by kanishka-azimi** [comment]
Okay, maybe wait for dust to settle for a while.
